<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.0.36525.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libraries\Iciclecreek.Azure.Storage.Memory\Iciclecreek.Azure.Storage.Memory.csproj" />
    <ProjectReference Include="..\Libraries\Iciclecreek.Azure.Storage.FileSystem\Iciclecreek.Azure.Storage.FileSystem.csproj" />
    <ProjectReference Include="..\Libraries\Iciclecreek.Azure.Storage.SQLite\Iciclecreek.Azure.Storage.SQLite.csproj" />
  </ItemGroup>
</Project>
